Update service info artifact list to add seqcol and rename refget
ga4gh/TASC pull request #48
Opened 2024-02-21 18:01 UTC by tcezard

The [sequence collection specification](https://seqcol.readthedocs.io/en/latest/specification/) is currently ongoing GA4GH product approval and as part of this process we're proposing to add a new type to the TASC registry.

The development of the sequence collection specification also saw the rebranding of refget as a more generic term encompassing both refget.sequence (formally refget) and refget.seqcol (for sequence collection)

2024-05-22 20:44 UTC, mamanambiya requested changes
Thanks @tcezard for submitting this PR. According the submission guidelines, the entries must be ordered alphabetically. I think `refget.seqcol` should come before `refget.sequence`.

2024-07-03 16:48 UTC, mamanambiya approved these changes

2024-07-04 07:28 UTC, mbaudis commented
No objections.

2024-07-04 22:21 UTC, jmarshall commented
The proposed artifact values do not conform to the expected kebab case format.

Either TASC should consider widening the expect format e.g. to allow period-based hierarchy in these values (so the regex might be `^([a-z][a-z0-9]*)([.-][a-z0-9]+)*$`), or the sequence collection authors should consider using `refget-seqcol` and `refget-sequence`.

2024-07-05 09:26 UTC, mbaudis commented
Ouch, right @jmarshall. So the question here is if it is `refget` with dot indication for a parent.child relation (_i.e._ description and regex have to be amended) or if they are "independent" `refget-seqcol` and `refget-sequence`.

2024-07-07 11:58 UTC, jmarshall commented
This is the first time we have removed an extant artifact value from this list: here is it `refget`, which is being renamed. The only [process defined](https://github.com/ga4gh/TASC/tree/main/service-info#process) in this list's README is for the addition of new items. So we need to think about what the process should be for removing or renaming items.

One purpose of this registry list is to prevent collisions — including collisions involving historical values, which are likely to be still in use by older servers. So IMHO entries should never be removed. In that case we would leave the `refget` entry as is, adding subfields to the effect of

```
…, "status": "superseded", "note": "renamed to …whatever… as of …date…", …
```

Another purpose of this registry is to attest that artifact values are being used appropriately and as per their registry listing. In this case I would expect to see the proposed artifact values listed in the service-info parts of the respective specs, and for the renaming in the sequence protocol I'd expect to see a discussion of older servers returning `"type": { "group": "org.ga4gh", "artifact": "refget", … }` in their service-info responses.

As far as I can see, the [current seqcol specification](https://seqcol.readthedocs.io/en/latest/specification/) does not state what the contents of the generic part of the service-info response should be at all. I didn't see any PRs making any additions to specify the proposed value.

For the refget / sequence protocol, the [current specification (v2.0)](http://samtools.github.io/hts-specs/refget.html#method-fetch-information-on-the-service) states (by example, not in clearly normative text) that the service-info response should include `"artifact": "refget"`, i.e., the existing artifact value in the registry, prior to this renaming. I didn't see any PRs or similar or other drafts making any changes to the service-info part of the protocol or specification.

(I may have missed seeing the relevant specification drafts. It would be helpful if the opening comment of this PR had pointed to the relevant documents or updates, e.g. as PRs #31 and #41 did. I hope the refget/seqcol authors will do so now.)

In my opinion, until TASC has seen the specification drafts or PRs using the proposed artifact values, we cannot merge these changes to the registry.

2025-02-26 21:47 UTC, jmarshall commented
@tcezard @andrewyatz Today I have rechecked the current specifications and nothing has changed in this respect compared to my comments from last July: the [current seqcol specification](https://ga4gh.github.io/refget/seqcol/#31-service-info) does not state what the contents of the generic part of the service-info response (notably `type.artifact`) should be; the [current refget specification](https://ga4gh.github.io/refget/sequences/#method-fetch-information-on-the-service) still shows only `"artifact": "refget"` in an example.

What is the state of this request to add one artifact value and rename another?

2025-02-27 10:59 UTC, tcezard commented
@jmarshall Thanks for the reminder. I've just opened a [PR](https://github.com/ga4gh/refget/pull/93) in the new refget.sequence specification location which also update the sequence collection description of the service-info.

2025-02-27 11:02 UTC, tcezard commented
About the question about using dot `.` or dash `-` to separate the words. @mbaudis  interpretation is correct and we intended to convey the hierarchical relationship between refget and its component. If this is a blocker do let me know and I can bring it up again at our next meeting.

2025-03-05 16:59 UTC, tcezard commented
In relation to the `artifact: refget` being remove. Should it be kept in the list of artifact ?

2025-03-05 23:04 UTC, jmarshall commented
Thank you very much for updating this to use `-` as a word separator. Don't worry about the keeping-`refget`-in-the-list thing — this is really an issue for TASC IMHO and we will sort this out appropriately when merging the PR.

2025-05-27 10:08 UTC, jmarshall commented
At this time, the current specifications for both [refget](https://ga4gh.github.io/refget/sequences/#example-json-request-and-response_1) and [seqcol](https://ga4gh.github.io/refget/seqcols/#example-of-a-service-info-response) include example service-info responses that show the `refget-sequence` and `refget-seqcol` artifact values respectively, as per this PR.

2025-05-27 20:30 UTC, merged